name: Deploy

on:
  workflow_call:
    inputs:
      cloudfront-distribution-id:
        required: true
        type: string
      bucket-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: aws s3 sync ./build s3://${{ inputs.bucket-name }}/ --delete --exclude service-worker.js --exclude index.html
      
      - name: Deploy index.html
        run: aws s3 cp ./build/index.html s3://${{ inputs.bucket-name }} --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --metadata-directive REPLACE
      
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront-distribution-id }} --paths "/*"
